name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # only run if required secrets exist
    if: ${{ secrets.DEPLOY_HOST && secrets.DEPLOY_USER && secrets.DEPLOY_SSH_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Preflight – verify required secrets
        run: |
          : "${{ secrets.DEPLOY_HOST?Missing DEPLOY_HOST }}"
          : "${{ secrets.DEPLOY_USER?Missing DEPLOY_USER }}"
          : "${{ secrets.DEPLOY_SSH_KEY?Missing DEPLOY_SSH_KEY }}"
          echo "Secrets present. Continuing."

      - name: Basic build check
        run: |
          npm ci
          node -e "console.log('build ok')"

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host:     ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key:      ${{ secrets.DEPLOY_SSH_KEY }}
          port:     ${{ secrets.DEPLOY_PORT || '22' }}
          script: |
            set -e
            if [ ! -d /opt/yt2x ]; then sudo mkdir -p /opt/yt2x && sudo chown $USER /opt/yt2x; fi
            cd /opt/yt2x
            if [ ! -d .git ]; then
              git init
              git remote add origin $GITHUB_SERVER_URL/${{ github.repository }}
            fi
            git fetch --all
            git reset --hard origin/main
            docker compose up -d --build

      - name: Post-deploy status
        uses: appleboy/ssh-action@v1.2.0
        with:
          host:     ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key:      ${{ secrets.DEPLOY_SSH_KEY }}
          port:     ${{ secrets.DEPLOY_PORT || '22' }}
          script: |
            docker compose ps
            docker compose logs --tail=50
